### ISSUE TITLE
People don't know how to know what is public in Confluence

### ISSUE THREAD

**Issue by nedbat** [edx/open-source-process-wg#12]
I've answered this a few times in Slack:
> [Ned Batchelder](https://app.slack.com/team/UD9KBSYTB)  [3 minutes ago](https://edx-internal.slack.com/archives/C1LM7G955/p1643990349217759?thread_ts=1643986858.322219&cid=C1LM7G955)
It is hard to decipher Confluence permissions to know what can be seen. We’ve tried to name spaces that are internal only with “Internal” in their name.
> 
> [Ned Batchelder](https://app.slack.com/team/UD9KBSYTB)  [3 minutes ago](https://edx-internal.slack.com/archives/C1LM7G955/p1643990376858889?thread_ts=1643986858.322219&cid=C1LM7G955)
For individual pages, I have a chrome extension that re-opens the page in incognito mode to test it empirically.

The extension: https://chrome.google.com/webstore/detail/open-in-incognito/peacnpgnojjkmbepjndigjojeoipkflb

**Comment by hurtstotouchfire** [comment]
https://github.com/openedx/tcril-engineering/issues/35

**Comment by sarina** [comment]
@hurtstotouchfire that's not the conclusion I would take from that ticket. The first task is to figure out who uses the wiki and why. Then to use those personas to compare various wikis. This process will take awhile and is not guarenteed to result in a new wiki choice.

Regardless, this work is as of yet completely unprioritized. If we do prioritize it, it will take some time for those first two steps, and additional time to migrate the existing wiki to a new instance, swap links or figure out forwarding, and communicate to the community.

**Comment by sarina** [comment]
@nedbat can't you look at the view restrictions on the page to see what's public? I can't check since I can't access internal pages. You can click the lock button next to the Share button (if it's red and locked, it's certainly not visible to the public; if it's blue and open, it _might_ be visible to the public). You can click Inspect Permissions

![image](https://user-images.githubusercontent.com/1985317/153209077-6087783d-7e62-4fea-8dfc-b23737d04fc2.png)

Put in my name (or another community member) to see if it's visible to us:

![image](https://user-images.githubusercontent.com/1985317/153209176-f5cb5e74-dcd1-4c20-af6c-820db5752ccd.png)

**Comment by nedbat** [comment]
@sarina Thanks, you are right: Confluence has definitely improved the inspectability.  I was repeating old information :(

**Comment by jmbowman** [comment]
Now that we have 2 separate Confluence instances (one all private and the other mostly public), can we consider this resolved?  If not, what else is needed in this area?

**Comment by jristau1984** [comment]
I would think this can be closed, being as it is just knowing how to use Confluence features correctly.

However, the title gives me pause... who are the "people"?  Have they been informed of this?  Was that information accepted as sufficient by them?
