### ISSUE TITLE
Write plan for changing how release tags and branches are named

### ISSUE THREAD

**Issue by e0d** [edx/open-source-process-wg#94]
I'd like input from 2U operations on what a reasonable runway would be for updating how tags and branches are named by CD systems and other automation.

The rationale is in [this ADR](https://github.com/openedx/.github/pull/36/files).  I'd like to include the agreed upon grace period in the ADR. tl;dr: deploying edx-platform creates tags and branches named "release-\*", and tCRIL wants them to be named "2u/release-\*".  EVEN BETTER: get rid of the tags or branches in the openedx-org repo completely.

Acceptance criteria:
- Write a plan for renaming or removing the tags and branches
 
```[tasklist]
# Discovery items
- [x] Find out how GoCD configuration has to change: edx-internal has hardcoded branch names: edx/edx-internal/gocd/manually-created-pipelines/edxapp.yaml
- [x] What needs to change in the security process?
- [x] Get other details of things to update
- [x] How do we change things so that we no longer produce release openedx wiki pages
- [x] Should build/test/release use something different to create the open releases?
- [x] Estimate the work to update everything
```

Repos to investigate:
- tubular
- edx-internal
- configuration
- edx-platform/openedx.yaml

**Comment by nedbat** [comment]
```[tasklist]

- [ ] Find out how GoCD configuration has to change
- [ ] We no longer produce release wiki pages
```

**Comment by timmc-edx** [comment]
Discovery:

- In edx-platform, there are three types of branches or tags involved:
  - There are tags with names like `release-2023-03-03-10.42` that represent actual releases (to prod/edge and stage, or just prod?)
    - 📂 I don't know what creates these
    - 📂 I don't know if anything uses these, but they're probably just for human reference
  - There are branches with names like `release-candidate-3979` which appear to be made for every merge that lands on master, only some of which turn into actual releases. These appear to be deleted after 2 weeks.
    - These seem to be created by an invocation of tubular's `cut_branch.py`
    - 📂 It is unclear what reads these, if anything. They may just be for human reference.
  - There is a singular branch called `release` that probably tracks the most recent release tag. This one is actually used in the Open edX named release branch-cutting process, so we don't want to get rid of it (?) but should probably rename it.
    - I believe this one is managed by tubular's `merge_branch.py`, which fast-forwards it after release.
    - 📂 Does anything use it other than the named release branch-cutting process?
  - And finally, a singular branch called `release-mergeback-to-master` that's probably somehow involved in the private patch process.
    - I think this is used when merging the release branch back into master... which is probably some outdated process that is no longer relevant.
- Just to make things confusing, there is an _unrelated_ mechanism in the private clone of edx-platform (which we actually deploy from, in order to patch privately) that has a singular `release-candidate` branch and tags like `release-20230303143256`, but also `release-2023-03-03-10.42`. This last category is probably fetched from the public repo and not actually used in the patch process.

**Comment by timmc-edx** [comment]
Proposed plan here, although I'm still gathering feedback on it from 2U engineers: https://github.com/edx/edx-arch-experiments/issues/212

**Comment by timmc-edx** [comment]
@e0d Does the plan in that ticket (https://github.com/edx/edx-arch-experiments/issues/212) look good? I think we want to rename the `release` branch to `2u/release` but otherwise keep it since it's currently part of the Open edX release process. The other tags and branches should be possible to remove from the public repo.

I reckon we could do this by April, with the understanding that there's a lot of CI code here that hasn't been touched in a long time and so there's a good chance of "unknown unknowns" that will cause delays.

**Comment by timmc-edx** [comment]
OK, that went faster than expected! `release` is renamed `2u/release` and the other branches/tags will stop being created. There's still some chance of having to back things out again, but I'm closing this planning ticket out.
